# Generated by Django 5.1 on 2024-08-23 20:00

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("img_link", models.TextField()),
                (
                    "article_link",
                    models.TextField(
                        default="https://www.nytimes.com/spotlight/learning-stem"
                    ),
                ),
                ("excerpt", models.CharField(max_length=500)),
                ("date_published", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("profile_img_link", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("link", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nonprofits", "Non-Profits"),
                            ("onlinecourses", "Online Courses"),
                            ("studentorganizations", "Student Organizations"),
                        ],
                        max_length=75,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(blank=True, max_length=70)),
                ("state", models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="TutoringRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_courses",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("ACT", "ACT"),
                            ("SAT", "SAT"),
                            ("NYC SHSAT", "NYC SHSAT"),
                            (
                                "Grade/Regents Level Sciences",
                                "Grade/Regents Level Sciences",
                            ),
                            ("Grade/Regents Level Math", "Grade/Regents Level Math"),
                            (
                                "Advanced Placement Biology",
                                "Advanced Placement Biology",
                            ),
                            (
                                "Advanced Placement Chemistry",
                                "Advanced Placement Chemistry",
                            ),
                            (
                                "Advanced Placement Physics 1",
                                "Advanced Placement Physics 1",
                            ),
                            (
                                "Advanced Placement Statistics",
                                "Advanced Placement Statistics",
                            ),
                            (
                                "Advanced Placement Calculus AB",
                                "Advanced Placement Calculus AB",
                            ),
                            (
                                "Advanced Placement Calculus BC",
                                "Advanced Placement Calculus BC",
                            ),
                            (
                                "Advanced Placement Computer Science A",
                                "Advanced Placement Computer Science A",
                            ),
                        ],
                        max_length=286,
                    ),
                ),
                ("additional_information", models.TextField(blank=True)),
                ("request_approved", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
